config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'
  get 'projects/dashboard'
  post 'projects/create'
  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, :description, :state, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def create
    @project = Project.create(name: params[:name], description: params[:description], start_date: params[:start_date], end_date: params[:end_date], state: params[:state])
  end

  def dashboard
    if params[:state].present?
      @projects = Project.where('state = ?', params[:state])
    else
      @projects = Project.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GestorProyectos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/create.html.erb
<%= link_to 'Volver al Inicio', root_path %>
<% if @project.errors.any? %>
    <div id="error_explanation">
        <h2>No se puede guardar el post por las siguientes razones:</h2>
        <ul><% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% else %>
    <h1>¡Registro exitoso!</h1>
<% end  %>

app/views/projects/dashboard.html.erb
<table class="table">
    <tr>
        <th>Nombre</th>
        <th>Descripción</th>
        <th>Fecha de Inicio</th>
        <th>Fecha de Término</th>
        <th>Estado</th>
    </tr>
    <% @projects.each do |p| %>
        <tr>
            <td><%= p.name %></td>
            <td><%= p.description %></td>
            <td><%= p.start_date %></td>
            <td><%= p.end_date %></td>
            <td><%= p.state %></td>
        </tr>
    <% end %>
</table>
<form>
        <label for="state">Estado</label>
        <select name="state">
            <option value="Propuesta">Propuesta</option>
            <option value="En progreso">En progreso</option>
            <option value="Terminado">Terminado</option>
        </select>
        <button type="submit" class="btn btn-primary">Buscar</button>
</form>


<%= link_to 'Volver al Inicio', root_path %><br>

app/views/projects/index.html.erb
<form method="POST" action="/projects/create">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

    <div class="form-group">
        <label for="name">Nombre</label>
        <input name="name" class="form-control">
    </div>

    <div class="form-group">
        <label for="description">Descripción</label>
        <input name="description" class="form-control">
    </div>

    <div class="form-group">
        <label for="start_date">Fecha de Inicio</label>
        <input type='date' name="start_date" class="form-control"></input>
    </div>
    
    <div class="form-group">
        <label for="end_date">Fecha de Término</label>
        <input type='date' name="end_date" class="form-control"></input>
    </div>

    <div class="form-group">
        <label for="state">Estado</label>
        <select name="state">
            <option value="Propuesta">Propuesta</option>
            <option value="En progreso">En progreso</option>
            <option value="Terminado">Terminado</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>

<%= link_to 'Ir al Dashboard', projects_dashboard_path %><br>